# Versions of PHP to test against
php:
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  
# Versions of WordPress to test against
# WP_VERSION = WordPress version number
# WP_MULTISITE = Enable Multisite?
env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=3.6 WP_MULTISITE=0
  - WP_VERSION=3.5.2 WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1
  - WP_VERSION=3.6 WP_MULTISITE=1
  - WP_VERSION=3.5.2 WP_MULTISITE=1
